# Generated by Django 2.1.4 on 2018-12-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_registrohoraextra_horas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='funcinario',
            new_name='funcionario',
        ),
    ]
